### ISSUE TITLE
Ability to change diagram theme

### ISSUE THREAD

**Issue by biddster** [AleksandarDev/vscode-sequence-diagrams#1]
This is such a good extension. Please can we have the option to change the diagram theme?

**Comment by AleksandarDev** [comment]
@biddster Like in light vs dark theme or hand drawn vs simple?

**Comment by biddster** [comment]
Hand drawn vs simple please.

**Comment by AleksandarDev** [comment]
@biddster 
Version 0.2.0 is now available on marketplace.

You can change style by placing `"sequencediagrams.diagram.style": "simple"` in your vscode configuration.

**Comment by biddster** [comment]
Fabulous, many thanks @AleksandarDev .
