### ISSUE TITLE
Support for deactivate?

### ISSUE THREAD

**Issue by mseliger** [AleksandarDev/vscode-sequence-diagrams#10]
Some elements like "deactivate" see here:
https://www.websequencediagrams.com/examples.html
are not supported by vscode-sequence-diagrams (the elements which are described under the chapter Lifeline Activation and Destruction)

**Comment by AleksandarDev** [comment]
We are using [js-sequence-diagrams](https://bramp.github.io/js-sequence-diagrams/) to render the diagrams and it has limited syntax.
