### ISSUE TITLE
Export to PNG: Encoding problem of German "Umlaute" (ä,ö,ü)

### ISSUE THREAD

**Issue by ml-eds** [AleksandarDev/vscode-sequence-diagrams#18]
Hi,

thanks for creating this awesome VS Code extension!!

I just encountered the following bug (macOS 10.14.6, VS Code Version: 1.39.2)

To reproduce:

1. Save simple sequence diagram with ä,ö,ü characters with UTF-8 encoding. 

For example:

    Title: Rückmeldung/In Bearbeitung Statuswechsel
    CRM->>CRM: 1. Status: Rückmeldung

2. Export to png.

Expected: ä,ö,ü are printed correctly in png
Actual: See attached image
![Bildschirmfoto 2019-10-23 um 12 57 46](https://user-images.githubusercontent.com/35484461/67386275-ef48c780-f594-11e9-9f78-459ba2d4f77f.png)

**Comment by AleksandarDev** [comment]
@ml-eds Should be fixed with new version `0.4.0`
