### ISSUE TITLE
Plugin not rendering the diagram

### ISSUE THREAD

**Issue by mitasoft** [AleksandarDev/vscode-sequence-diagrams#23]
extension version v0.4.0

trying to render a sequence diagram based on the following:
```
Andrew->China: Says Hello
Note right of China: China thinks\nabout it
China-->Andrew: How are you?
Andrew->>China: I am good thanks!
```

Nothing is rendered in the diagram preview

**Comment by homorozeanu** [comment]
Same problem here!

Plugin version: v0.4.0
VSCode version: 1.50.1

Any update?

**Comment by JoeMcB** [comment]
Did some digging and it appears the extension is using either imprecise permissions or old webview resource access.  In either case, updating the asset access fixes it. Attached a PR.

**Comment by yzalvov** [comment]
I am not able to use this extension of v0.4.1 with Visual Studio Code v1.51.0. 

In my `test.seqdiag` I try the same content as @mitasoft and there's nothing rendered on the Sequence Diagram tab. I can see an error in the vscode debug console (screenshot below): `Cannot read property 'webview' of undefined`

Tried a completely fresh vscode install with only this extension – same negative result.

<img width="1222" alt="Screenshot 2020-11-08 at 17 26 00" src="https://user-images.githubusercontent.com/25827414/98467702-c7e88b00-21e7-11eb-8314-0be7c5fdba09.png">

**Comment by JoeMcB** [comment]
Resolved dual build systems with https://github.com/AleksandarDev/vscode-sequence-diagrams/pull/25

I _think_ that will fix the current master issue but need to see it repubished to verify.

**Comment by yzalvov** [comment]
Great, thank you @JoeMcB !

I guess we have to wait for @AleksandarDev to make us all happy by a merge?

**Comment by yzalvov** [comment]
@JoeMcB please advise, how to fix locally before that PR merged?

**Comment by AleksandarDev** [comment]
@JoeMcB I'm getting following error after merging your changes. Maybe tsconfig.json is required after all.

```
❯ yarn vscode:prepublish
yarn run v1.22.4
warning vscode-sequence-diagrams@0.4.1: The engine "vscode" appears to be invalid.
$ webpack --mode production
[webpack-cli] Compilation finished
assets by status 538 KiB [cached] 15 assets
./src/extension.ts 39 bytes [built] [code generated] [2 errors]

ERROR in ./src/extension.ts
[tsl] ERROR
      TS18002: The 'files' list in config file 'tsconfig.json' is empty.

ERROR in ./src/extension.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: error while parsing tsconfig.json
    at Object.loader (C:\Users\Aleks\Documents\GitHub\vscode-sequence-diagrams\node_modules\ts-loader\dist\index.js:19:18)

webpack 5.2.0 compiled with 2 errors in 3007 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by JoeMcB** [comment]
Apologies for that.  I'm not familiar with the publishing aspect here and suspect there's a configuration issue going from a development env to a package.  I'll revisit when I can.

**Comment by rafapolo** [comment]
15,115 installs and waiting a fix for four months now :/

**Comment by AleksandarDev** [comment]
@rafapolo I'm currently unable to maintain this extension. Feel free to help @JoeMcB fixing the issue. I'll merge and publish new version moment it builds.

**Comment by rafapolo** [comment]
Hi @JoeMcB, any thoughts on this? This is such a nice and useful extension! It is a shame it is dead.

**Comment by yzalvov** [comment]
Hi @JoeMcB yes mate please share some love 💕

**Comment by JoeMcB** [comment]
I'll take a look when I can.  2 different build tools are being used between dev and prod.  I encourage anyone interested to check this code out and work on it themselves.  Best way to learn is to try!

**Comment by JoeMcB** [comment]
PR fixing build is ready @AleksandarDev

**Comment by AleksandarDev** [comment]
@JoeMcB Thanks for the PR. Build issues are now resolved and I have published the extension. 
But the issue of diagram not rendering is still present. I see no errors regarding that but I see error when "Preview" tab is closed:

![image](https://user-images.githubusercontent.com/643171/105612256-2a9afd00-5dbb-11eb-80ae-207c54403779.png)

**Comment by JoeMcB** [comment]
🤕 
I'll check it out.  It works in dev!

**Comment by jvitrifork** [comment]
It is still an issue. Have you had the time to have a look at it?
