### ISSUE TITLE
Project level diagrams

### ISSUE THREAD

**Issue by weedkiller** [AleksandarDev/vscode-sequence-diagrams#28]
Hello, this is very nice, if you included a screen shot or image on the main page, many people will download it.

- [ ] Can you please support the diagrams at the project level like [so ](https://marketplace.visualstudio.com/items?itemName=AlexShen.classdiagram-ts&ssr=false#overview)

- [ ] Export/Save Image or HTML to disk

No longer maintained sadly https://github.com/lucalanca/grunt-angular-architecture-graph, but some help

**Comment by AleksandarDev** [comment]
@weedkiller Extension already supports saving PNG and SVG to disk. 
As for project level diagram, I'm not sure I understand what that diagram is showing? If you have `.seqdiag` file in your project files, diagram will show if you just open that file.

**Comment by weedkiller** [comment]
Hi Alek, if you see the picture or the link above you will see, we can create the boxed, component level diagrams, hope that helps. It would awesome to have that in your plugin 👍

**Comment by AleksandarDev** [comment]
> Hi Alek, if you see the picture or the link above you will see, we can create the boxed, component level diagrams, hope that helps. It would awesome to have that in your plugin 👍

I understand you would like to create class diagrams? That is kinda out-of-scope for this extension since this is focused on sequence diagrams.
