### ISSUE TITLE
Ability to create other type of diagrams.

### ISSUE THREAD

**Issue by TheTechOddBug** [AleksandarDev/vscode-sequence-diagrams#4]
Hi.

Maybe this feature I'd like to see here is not the original target of this plugin but it would be great to have the ability to write other kind of diagrams like class diagrams, state diagrams and so on. The hand-writing flavour is great. Congratulations for this plugin!

Thanks in advance.

**Comment by AleksandarDev** [comment]
Hi @TheTechOddBug ,

This is an extension for library that only supports sequence diagrams at the moment.

https://bramp.github.io/js-sequence-diagrams/

You can try requesting the feature there.
