### ISSUE TITLE
Support multi-line messages in editor

### ISSUE THREAD

**Issue by kfarner** [AleksandarDev/vscode-sequence-diagrams#5]
In the sequence diagrams I use notes to describe JSON payload of the messages. Since the messages are restricted to be a single line in the editor it is hard to edit it.

It would have been nice to be able to break it into multiple lines in the editor. Like this for example:

    Client->Server: POST /sessions/join
    Note right of Client: \
      {  \
          Id: <some-id>, \
          Name: <name>, \
      }
    Server->Client: 200 OK

**Comment by AleksandarDev** [comment]
Hi @kfarner ,

This is an extension for library that only supports sequence diagrams at the moment.

https://bramp.github.io/js-sequence-diagrams/

You can try requesting the feature there.

PS. This could be done in the extension, but I think the source library is better place for this kind of features.
