### ISSUE TITLE
Only .seqdiag files supported

### ISSUE THREAD

**Issue by michaelkrone** [AleksandarDev/vscode-sequence-diagrams#8]
Since it is an important feature of sequece diagrams to be created with simple text files and can be read and opened as those, this extension should not care about file extensions - or should at least not only support `.seqdiag` extensions.

Personally I never saw a `.seqdiag` file. Some sequence diagram tools use `.diag` as extension, I would prefer `.txt` which would enable every user to open the diagram in every environment.
Maybe you can explain the restriction to `.seqdiag` file extensions.

**Comment by AleksandarDev** [comment]
If we set `.txt` as `Sequence Diagram` language association, Visual Studio Code would open any `.txt` file as sequence diagram by default which is not what we want. 

Solutions: 

- You can however open any file and select `Sequence Diagram` as language type (in the right corner of Visual Studio Code's status bar), it will not care about file extension. 
- You can also configure any extension to be opened as `Sequence Diagram` by clicking on language and selecting `Configure File Association for '.diag'...` where you can select any language to be default for that file extension. 
- Or even edit the user/workspace preferences as you require: https://stackoverflow.com/a/36789145

**Comment by AleksandarDev** [comment]
![image](https://user-images.githubusercontent.com/643171/41159679-a4d53cb2-6b2d-11e8-8218-fa21f659aab2.png)

Note that the `Sequence Diagram` is selected as current language (lower right). 
Any file extension will open no problem (`test.abc` in example).

**Comment by michaelkrone** [comment]
Thank you @AleksandarDev. I had the false assumption only .seqdiag files can be viewed as diagrams. Selecting the language is a sufficient solution. Thank you for this useful extension.

**Comment by MarcoMedrano** [comment]
This tool is great!!!
Wonder if there is no another way to automatically select "**Sequence Diagram**" as language just when opened by the command **Show Sequence Diagram Preview**. without associating the file extension. 

Also would be nice and really useful to support **unsaved files**, at that point there is no file or extension name. The use case would be to just start diagraming to understand something (without the need of saving it) or just to share it by pasting the code into https://www.websequencediagrams.com
